### ISSUE TITLE
Unnecessary class

### ISSUE THREAD

**Issue by cngondo** [BrianLusina/MovieReel-app#1]
How are you using [this class](https://github.com/BrianLusina/MovieReel/blob/master/app/src/main/java/com/moviereel/moviereel/models/TvModel.java)?

**Comment by BrianLusina** [comment]
It is a contract for the TV shows item which will be pulled from the TV API endpoint, I haven't yet pushed this class.

**Comment by cngondo** [comment]
And you still haven't pushed until now
