### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by cngondo** [BrianLusina/MovieReel-app#2]
1. Inline comments on your code
2. Detailed README
3. Provide link to the hosted application

**Comment by BrianLusina** [comment]
1. I will definitely use inline comments
2. I shall update the readme
3. I haven't yet hosted it, but I will add it to Appetize today.

**Comment by cngondo** [comment]
No links yet!!

**Comment by BrianLusina** [comment]
It's the one generating the large memory dumps
So I removed the link to check the errors. I shall put it back up this evening

**Comment by BrianLusina** [comment]
Link put up. I fixed the memory dump issue. Had something to do with Jack compiler not working with a certain library.
